language: c
sudo: false

env:
 - PATH="$HOME/texlive/bin/x86_64-linux:$PATH"

before_install:
 - true

install:
  - echo "Installing LaTeX and LaTeX packages."
  - curl -L -o texlive.tar.gz https://github.com/yihui/ubuntu-bin/releases/download/latest/texlive.tar.gz
  - tar -C "$HOME/" -zxf texlive.tar.gz
  - tlmgr update --self
  - tlmgr install newunicodechar mathpartir pgf pgfplots bera float cancel pgfopts elocalloc environ savesym bbding wasy wasysym epigraph
  - echo "Finished installing LaTeX and LaTeX packages."
  # ################## #
  # Actual LaTeX build #
  # ################## #
  - pdflatex -halt-on-error -interaction=nonstopmode main.tex
  - bibtex main
  - pdflatex -halt-on-error -interaction=nonstopmode main.tex
  - pdflatex -halt-on-error -interaction=nonstopmode main.tex
  - pdflatex -halt-on-error -interaction=nonstopmode main.tex
  # ################## #
  # End of LaTeX build #
  # ################## #
  - bash ./auto-push-gh-pages.sh

script:
  - true